#!/usr/bin/env python

def build(ctx):
    ctx.program(
        source=[
            'jogma.c',
            'http.c',
            'jack.c',
            'flac.c',
            'net.c',

            'main.c'
        ],

        use=[
            'FLAC',
            'JACK',

            'http_parser',
            'b64',
        ],

        lib=['m'],

        includes=['..', '../include'],
        target='jogma')
